### ISSUE TITLE
Use MovingPandas

### ISSUE THREAD

**Issue by anitagraser** [movingpandas/qgis-processing-trajectory#18]
This plugin should be turned into a wrapper for the [MovingPandas library](http://movingpandas.org)

**Comment by kinow** [comment]
If anyone searches for stop, stop detection algorithm, etc, in this repository, see linked & closed issue. This issue about using MovingPandas includes the stop detection part :tada: 

Thanks @anitagraser !

**Comment by anitagraser** [comment]
Started in https://github.com/movingpandas/qgis-processing-trajectory/commit/1dd5cd7e96b73755199d5878b4297df0d05387ce

**Comment by anitagraser** [comment]
This is ongoing. The functionality of previous Trajectools releases is already covered by the new dev version.
