### ISSUE TITLE
Couldn't load plugin 'processing_trajectory'  ModuleNotFoundError: No module named 'movingpandas' 

### ISSUE THREAD

**Issue by picEmily** [movingpandas/qgis-processing-trajectory#27]
![图片](https://github.com/movingpandas/qgis-processing-trajectory/assets/55122724/31565cdd-5960-4907-866a-89ac7b130a14)

Couldn't load plugin 'processing_trajectory' 

ModuleNotFoundError: No module named 'movingpandas'

**Comment by anitagraser** [comment]
Please follow the installation instructions https://github.com/movingpandas/qgis-processing-trajectory/blob/main/README.md

**Comment by anitagraser** [comment]
duplicates https://github.com/movingpandas/qgis-processing-trajectory/issues/24
