### ISSUE TITLE
Make HomeWorkAttack optional?

### ISSUE THREAD

**Issue by marklit** [movingpandas/qgis-processing-trajectory#30]
The HomeWorkAttack processing plugin is the only one in this package that relies on scikit-mobility. 

scikit-mobility needs Python's headers installed. ``C:\Program Files\QGIS 3.38.0\bin\python-qgis.bat`` won't have access to them on a fresh install of Windows and Visual C++ 14.0. I haven't found clear instructions online for getting them installed on Windows 11 the way the python-dev package would be installed on Linux Systems.

Without scikit-mobility as a dependency, everything else will install with the Python REPL inside of QGIS' UI or via the python-qgis.bat script mentioned.

This could help more users try your plugin without jumping through conda hurdles or needing to head to Google to get everything working.

**Comment by marklit** [comment]
Thank you.

**Comment by marklit** [comment]
QGIS is reporting the latest stable build is v2.1 from May 20th. Are you going to push a new stable version to their plugin server soon?

**Comment by anitagraser** [comment]
> Are you going to push a new stable version to their plugin server soon?

Yes

**Comment by anitagraser** [comment]
@marklit Trajectools 2.2 just landed in https://plugins.qgis.org/plugins/processing_trajectory/#plugin-versions 
Please give it a try.

**Comment by marklit** [comment]
It's working now, thanks.
