### ISSUE TITLE
Usage query: visualizing gaps in trajectories

### ISSUE THREAD

**Issue by benparkergit** [movingpandas/qgis-processing-trajectory#33]
To visualize a trajectory with a dashed line where there are gaps of more than 6 hours in AIS records, I have this process: 

1. Make a "plain" trajectory from the AIS points
2. Run "Split trajectories at observation gaps" on the trajectory points from step 1 with a 6 hour setting
3. Display the original trajectory as dashed line and the result of step 2 as solid line on top. Remove other points and lines generated. 

I have removed colors in this example to simplify but I have kept the original AIS points to show the process. 

Question: Is this process OK or could I do it more simply? 

![image](https://github.com/user-attachments/assets/55cf1fbb-21a2-4873-8575-d41d798e090e)

**Comment by anitagraser** [comment]
The approach you describe is good. Currently, there is no other more convenient solution.

**Comment by anitagraser** [comment]
We can discuss how a more convenient solution would look like. For that, please head over to https://github.com/movingpandas/qgis-processing-trajectory/discussions and start a thread there.

If you already have a specific enhancement idea, you can file it in https://github.com/movingpandas/qgis-processing-trajectory/issues as enhancement request.
