### ISSUE TITLE
Split the stop duration field into two inputs

### ISSUE THREAD

**Issue by lgouzin** [movingpandas/qgis-processing-trajectory#36]
The stop duration item could be split into two fields, one for values, and one for time units. The current way is a bit confusing, does it take an 's', does it defaults to seconds, etc..

**Comment by lgouzin** [comment]
Yes that's correct. Did I enter them at the wrong place?

**Comment by anitagraser** [comment]
Yes but don't worry, I moved them to the plugin issue tracker now
